[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pybind11>=2.10.1",
    "cmake>=3.22",
    "scikit-build>=0.15",
]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
